version: 0.0
os: linux
files:
  - source: /scripts/index.html
    destination: /var/www/html/
  - source: /scripts/teste.txt
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root